server:
  port: 8089

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: qwerty
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false